[project]
name = "everywhere-any"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip>=25.1.1",
    "click>=8.1.7",
    "python-dotenv>=0.21.0",
    "questionary>=1.10.0",
]
